version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.

  # MySQL
  MYSQL_DATABASE: instacart_db
  MYSQL_HOST: 192.168.1.12
  MYSQL_PASSWORD: "{{env_var('DB_PASSWORD')}}"
  MYSQL_PORT: 3306
  MYSQL_USER: "{{env_var('DB_USER')}}"
  # Snowflake
  SNOWFLAKE_USER: "{{env_var('SNOW_USER')}}"
  SNOWFLAKE_PASSWORD: "{{env_var('SNOW_PASSWORD')}}"
  SNOWFLAKE_ACCOUNT: "{{env_var('SNOW_ACCOUNT')}}"
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
